# Generated by Django 2.2.14 on 2021-11-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utm_tracker', '0005_auto_20210809_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsource',
            name='medium',
            field=models.CharField(blank=True, help_text='utm_medium: Identifies what type of link was used, such as cost per click or email.', max_length=30),
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='source',
            field=models.CharField(blank=True, help_text='utm_source: Identifies which site sent the traffic.', max_length=30),
        ),
    ]
